### ISSUE TITLE
v0.4.1 looks broken on 32-bit architecture.

### ISSUE THREAD

**Issue by blackbeam** [Alexhuszagh/rust-lexical#15]
Hi.

Reported by @travismiller [here](https://github.com/blackbeam/mysql_async/pull/61#issuecomment-504770788).

Build log: https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25478919/job/n0x2jg84ypetvh24#L250

List of broken builds (only i686): https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25478919

**Comment by Alexhuszagh** [comment]
Thanks for catching this, I'll add in 32-bit tests if I can to the build process, major oversight on my part.

**Comment by Alexhuszagh** [comment]
@blackbeam This should be fixed in the latest commit, ff0f679. I've also added comprehensive unittests for various architectures, to ensure any commits test a wide variety of architectures, operating systems, and compilers. I'll deploy this shortly, once the issue in aarch64 (does not affect the correct parser, only compounds error in a lossy parser) has been patched.

**Comment by Alexhuszagh** [comment]
Fixed as of [v0.4.2](https://crates.io/crates/lexical-core/0.4.2).
