### ISSUE TITLE
[BUG] Improve Integer Serialization Performance

### ISSUE THREAD

**Issue by Alexhuszagh** [Alexhuszagh/rust-lexical#163]
## Description

As of `itoa` 1.0+, it has significantly faster performance for some use-cases than lexical. Since we use our integer writers for float formatting, this could lead to noticeable performance enhancements too for float formatting.

**Comment by plokhotnyuk** [comment]
ICYMI https://jk-jeon.github.io/posts/2022/02/jeaiii-algorithm/

**Comment by Alexhuszagh** [comment]
Oh this is incredible, thank you.

**Comment by Alexhuszagh** [comment]
Looking at this, we're getting excellent performance for 32-bit and smaller integers but I'm looking at the best way currently to fix performance for 64-bit integers due to the excessive branching causing issues. The 2-digit loop (the algorithm proposed by Alexandrescu) still generally is the best for integers larger than 32 bits from my testing but there should be a better way to optimize this.

**Comment by jk-jeon** [comment]
Just noticed this.

Giant branching is indeed a problem. I recall I did some research on doing this for 64-bit integers and concluded that it's just best to decompose it into 32-bit chunks (like one 2-digit chunk and two 9-digit chunks or something like that) rather than to operate directly on 64-bit integers, but don't have any real data.

What I can tell is that James did his own research after reading my post and came up with an updated version, which includes 64-bit: https://github.com/jeaiii/itoa

I recommend you to just have a look at what exact voodoo he did. It seems he decomposed a number into 4-8-8 chunks rather than 2-9-9 which I guess makes a lot of sense.

By the way, if I recall correctly, Andrei Alexandrescu is not really the one who invented the 2-digit grouping trick; it seems more like a folklore (like the famous Quake isqrt). He is just the one who popularized the trick, as far as I know.

**Comment by plokhotnyuk** [comment]
@Alexhuszagh @jk-jeon Thanks a bunch guys for your projects, blogs, and Reddit posts!

I reused your findings in my project: https://github.com/plokhotnyuk/jsoniter-scala

[Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L2110-L2148) you can see how I solved an issue of branch mis-predictions using [branch-less counter of digits](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L2378-L2380) and [8-byte store methods](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L2027-L2040) during serialization of 64-bit integers.

Below are throughput results for serialization of 128 values of 64-bit signed integers as a JSON array on different JVMs by different JSON libraries (including jsoniter-scala, smithy4sJson that uses jsoniter-scala under the hood, and jackson-module-scala that serialize using 3-digit grouping):
![image](https://github.com/user-attachments/assets/c4337ad7-87b2-458c-b980-aab84f34708f)

**Comment by Alexhuszagh** [comment]
Thanks for everyone's help on this, I was able to get quite incredible results with some optimizations for larger type sizes. This also had a noticeable impact on float serialization, so @jk-jeon I'll be drafting up a PR if these changes make any noticeable performance improvements in the reference dragonbox implementation.

Once again, thank you so much.

**Comment by jk-jeon** [comment]
@Alexhuszagh Thanks, I will also have a look at your implementation when I have time!

**Comment by jk-jeon** [comment]
I got a new proposal for 64-bit integers. Unfortunately I don't know if this really works or not (I don't have a rigorous proof), nor did decent randomized testing, so please just take it not so seriously.

Given the `u64` input `n`, the procedure goes as follows.
1. If `n` fits into 32-bits, then use the 32-bit routine. Otherwise, `n` is of at least 10-digits.
2. Compute the 128-bit result of `n * 15845632502852867519`, and perform shift-to-right by 33-bits.
3. The upper 64-bits represent the upper 10-digits and it must fit into 32-bits, so print them using the 32-bit routine except that if it's zero then we don't print anything.
4. Multiply `100` to the lower 64-bits, then the upper 64-bits of the output represent the following 2-digits. These two digits can be printed directly by one table lookup. (Since `n` is of at least 10-digits, these 2-digits cannot start with `0` if we got zero from the previous step.)
5. Now, from the remaining lower 64-bits, take the upper 32-bits, and then add 1 if and only if the other 32-bits are not all-zero (i.e., divide by $2^{32}$ and then perform ceiling).
6. The remaining 8-digits can be extracted by multiplying $10^{8}$ to the resulting 32-bits and then discarding the lower 32-bits. Just like the usual JEAIII algorithm, this can be done by repeating four times (1) multiply `100`, (2) take the upper bits and regard them as 2-digits number which can be directly printed, (3) keep the lower 32-bits and throw away the upper bits.

The main claim (which I could not justify) is that, once we are done with the first 12-digits (using a 64-bit version of JEAIII), we can halve the precision of the fractional part and then just keep going for the remaining 8-digits, without needing to extract the whole 8-digits and then recast into the 32-bit fractional form.

In pseudocode, something like:

```
utoa64 : (n : u64, buffer : char[]) -> size_t {
  if ((n & 0xffffffff) == n) {
    return utoa32(n as u32, buffer)
  }
  
  var y = umul128(n, 15845632502852867519)
  y = { (y.high() >> 33), (y.high() << 31) | (y.low() >> 33) }
  
  var written = y.high() == 0 ? 0 : utoa32(y.high() as u32, buffer)
  
  y = umul128(y.low(), 100)
  copy2bytes(buffer + written, digit_table + (y.high() * 2))
  written += 2
  
  var fractional = (y.low() >> 32) + ((y.low() & 0xffffffff) == 0 ? 0 : 1)
  repeat 4 times {
    fractional *= 100
    copy2bytes(buffer + written, digit_table + ((fractional >> 32) * 2))
    written += 2
    fractional &= 0xffffffff
  }
  
  return written
}
```

It sounds to me like this would be faster than alternatives... but again I don't even know if this really works or not.
