### ISSUE TITLE
parse api for char at time, incremental FromLexical

### ISSUE THREAD

**Issue by ratmice** [Alexhuszagh/rust-lexical#28]
In cases like #24 where you wish to parse a subset of the formats supported by lexical,
It would perhaps be nice if there was an API which would return an interim result, which could be fed back into the parse function along with the next character.

Then when parsing from e.g. a JSON float string representation, you could avoid malformed string representations, and convert to float in a single pass over the input.

**Comment by Alexhuszagh** [comment]
@ratmice I thought about this, however, there is no interim result really internally, since the result often isn't derived until the entire float is parsed to ensure the algorithm is correct. Also, providing a callback (which would be difficult to inline) for each character would be prohibitively costly.

I've found a way to parse a diverse number of inputs using bitflags to specify the input format, and use those bitflags to customize how the data is parsed, optimizing for specific input formats (there are currently 24 bitflags, or 2^24 possibilities, which is immense, but amazingly, with some smart optimizations, the default case is just as fast as before, and there's only small overhead with extensive customizations).

An example to use the new API will be:

```rust
extern crate lexical_core;  // ^0.6.4 or ^0.7.1

pub fn main() {
     // Use the pre-defined JSON format.
    let format = lexical_core::NumberFormat.JSON;
    println!("{:?}", lexical_core::parse_format("3.e7", format));    // Err
}
```

**Comment by ratmice** [comment]
Thanks for considering it anyways!

**Comment by rw** [comment]
I would also very much like this feature. I think it would be applicable to getting parsing correct (and still fast) in serde_json: https://github.com/serde-rs/json/issues/536

**Comment by Alexhuszagh** [comment]
@rw I've recently implemented support for standard-conforming, correct JSON parsing without a character-by-character API. Please see #24 and #35.

Examples of using it would be:

```rust
let format = NumberFormat::JSON;
i32::from_lexical_format(b"012", format).is_err(); 
assert!(f64::from_lexical_format(b"1E+2", format).is_ok());
assert!(f64::from_lexical_format(b"9.e+", format).is_err());
```

**Comment by Alexhuszagh** [comment]
I would gladly contribute this for inclusion into serde-json, since we implement a correct, robust, and JSON-conforming float and number parser.

**Comment by rw** [comment]
@Alexhuszagh I saw that while browsing your codebase, very cool :-]

AFAIK serde_json needs a byte-at-a-time parser to achieve its high performance. From what I can tell, your batch code "eats" the string byte by byte, internally. Do you think a conversion to byte-at-a-time would be hard?

**Comment by Alexhuszagh** [comment]
@rw This implements a partial parse, which does just that. The complete parser is implemented in terms of the partial parser, and just confirmed the entire input is consumed.

Since the inputs for a float parser are all valid ASCII, the parser operates on raw bytes intrinsically, and will stop when an invalid digit (including any non-ASCII) is found.

To both efficiently detect and parse a float, you can use the following code:

```rust
extern crate lexical_core;

// We want to signify we're using a JSON schema for the float.
let format = lexical_core::NumberFormat::JSON;

// Use the partial parser, which consumes as many bytes as possible, returning the number of parsed digits and the returned float.
let result = lexical_core::parse_partial_format::<f64>("3.0e7, \"a\": \"f\"", format);
println!("{:?}", result);  // (3e7, 5), meaning 5 bytes were processed and a the value is equal to 3e7.
```

**Comment by rw** [comment]
@Alexhuszagh My understanding is that parse_partial still requires an intermediate buffer, is that correct? I looked into using it earlier today for byte-at-a-time, but I don't think that would work.

A way to test this is: can you parse a float from something that implements io::Read?

**Comment by Alexhuszagh** [comment]
As far as using a byte-at-a-time parser, I'm not sure, the API isn't set to do that yet. It would be doable, but internally we accept a byte-slice or a type convertable to a byte slice. This would require some re-factoring on my part.

@rw I can look into refactoring for that purpose. Sorry, I was somewhat confused, that is not currently implemented, but it sounds like an excellent feature. Either open a feature request or I can look into doing that myself.

Thank you.

**Comment by rw** [comment]
@Alexhuszagh Because your library is so featureful, I think it would take me a while to understand the codebase. If there is any non-coding way I can help, please let me know! I might have time in two weeks to help more materially.

**Comment by Alexhuszagh** [comment]
@rw What could work, and I would be more than happy to do is gift the portions of the code relevant to float parsing to serde-json to ensure a correct parser is implemented, in case the current API is not satisfactory. I can look at implementing a parser in terms of `io::Read`, but at some level, we do need a forward iterable object (an iterator that can be constructed multiple times, can be iterated over forwards).

In short, at some level, an intermediate buffer will be required for the correct parsing, but we should be able to implement an abstraction in terms of io::Read regardless. This is because only ~700 significant digits can contribute to a floating-point number in decimal, so with the decimal point, we only need to worry about 688 total bytes being parser at a time, giving us a strict limit to avoid dynamic allocation.

So, this is definitely doable, but I'm open to a few different possibilities:
1). I help you implement just the parts of lexical (battle-tested, very stable) to implement a correct JSON-conforming float parser in serde-json.
2). I implement an API in terms of `io::Read`.

Just let me know what works best with other contributors, and I'll happily provide an expertise I can, or work to improve lexical for that aim.

**Comment by rw** [comment]
@Alexhuszagh Would you like me to make a fresh issue for this byte-at-a-time project?

**Comment by Alexhuszagh** [comment]
@rw That sounds great, thank you.
