### ISSUE TITLE
Tracking issue: atof for exact float parsing (hopefully for serde_json)

### ISSUE THREAD

**Issue by rw** [Alexhuszagh/rust-lexical#36]
This issue tracks the implementation of an atof function that could be used by serde_json. It is motivated by the parsing issues discussed in https://github.com/serde-rs/json/issues/536.

@Alexhuszagh Has provided background detail in https://github.com/Alexhuszagh/rust-lexical/issues/28. In particular, their `lexical` library has **lots** of testing, which provides a great foundation on which to build a customized atof function.

The direction that currently seems viable is to add a streaming atof function to `lexical-core`. It would operate on one byte at a time. This ought to allow serde_json to correctly parse JSON floats at high speed.

**Comment by ijl** [comment]
serde-json begins parsing a number without knowledge of whether the number should be an integer or float. Could a more general API handle this and for a stream of bytes return a u64, i64, or f64?

**Comment by Alexhuszagh** [comment]
@ijl This could be done, yes. I thought against it, because it seems like it's imposing conventions of languages that use JSON into lexical, but it has utility outside of merely JSON (think, for example, a compiler that doesn't use a lexer/parser combination and wants to classify a literal as a float or integer).

I'll have to think about this.

**Comment by Alexhuszagh** [comment]
I'm closing this since serde-json now uses their own private fork of lexical, and has this feature implemented well.
