### ISSUE TITLE
How to Parse int32 from "10e3"?

### ISSUE THREAD

**Issue by JesseAtSZ** [Alexhuszagh/rust-lexical#70]
How can I parse an integer from a string with scientific counting？
I am trying the following， but it does not work: 
```
const MY_FORMAT_BUILDER: u128 = lexical::NumberFormatBuilder::new()
    .build();
let options = lexical::ParseIntegerOptions::builder()
    .build()
    .unwrap();
assert_eq!(
    lexical::parse_with_options::<i32, _, MY_FORMAT_BUILDER>("10e3", &options),
    Ok(1000)
);
assert_eq!(
    lexical::parse_with_options::<i32, _, MY_FORMAT_BUILDER>("10E3", &options),
    Ok(1000)
```

**Comment by JesseAtSZ** [comment]
> How can I parse an integer from a string with scientific counting？ I am trying the following， but it does not work: ` const MY_FORMAT_BUILDER: u128 = lexical::NumberFormatBuilder::new() .build();
> 
> ```
> let options = lexical::ParseIntegerOptions::builder()
>     .build()
>     .unwrap();
> assert_eq!(
>     lexical::parse_with_options::<i32, _, MY_FORMAT_BUILDER>("10e3", &options),
>     Ok(1000)
> );
> 
> assert_eq!(
>     lexical::parse_with_options::<i32, _, MY_FORMAT_BUILDER>("10E3", &options),
>     Ok(1000)
> );`
> ```

**Comment by Alexhuszagh** [comment]
You cannot: that's exponent notation, AKA, not a valid integer. You may, however, parse it as a float and cast it to an integer.

```rust
let i: f32 = lexical_core::parse(b"1e3")?;
let x = i as i32;
```

This is because only digits (and the optional `+/-` sign) are considered valid for parsing integers, and this is generally accepted. Please note that you might get rounding error for some values about the size of the mantissa: AKA, values larger than can be exactly represented by a float.

For `f32`, this limit is `16777215`, and for `f64` this limit is `9007199254740991`, or 2^N -1`, where `N` is the number of bits in the mantissa (including the hidden bit).
