### ISSUE TITLE
[BUG] External crates cannot ensure `NumberFormat::is_valid`

### ISSUE THREAD

**Issue by CAD97** [Alexhuszagh/rust-lexical#78]
## Description

https://github.com/Alexhuszagh/rust-lexical/blob/d6f732237840917aba2f23db87f32ffbb1f1fa38/lexical-util/src/format_builder.rs#L914-L919

However, `NumberFormat` is not a publicly documented type, so this is referring to a deliberately `#[doc(hidden)]` functionality.

**Comment by Alexhuszagh** [comment]
I guess the solution then would be to document `NumberFormat`, but only document `is_valid` and `error`? I don't believe the rest should be exposed publicly. I've tried exposing the internal implementation intentionally, but it will stay as a packed struct around a `u128`, so I think this should be fine.

Exposing both I think is justified, since we should also give a diagnostic error if it isn't valid, or the caller wants better error handling.

**Comment by Alexhuszagh** [comment]
I've added the functions `format_is_valid` and `format_error`, both of which are documented and re-exported in `lexical_core` and `lexical` for this purpose. Both are `const fn`, so can be correctly evaluated.

**Comment by Alexhuszagh** [comment]
Fixed in [v0.8.3](https://crates.io/crates/lexical-core/0.8.3).
